apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-sentinel
  namespace: keycloak
spec:
  instances: 3
  db:
    vendor: postgres
    host: postgres-db.keycloak.svc.cluster.local
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    tlsSecret: tls-certificate-keycloak
  hostname:
    strict: false
  ingress:
    enabled: false
  features:
    enabled:
      # - fips
      - kerberos
  additionalOptions:
    - name: health-enabled
      value: "true"
    - name: metrics-enabled
      value: "true"
    - name: log-level
      value: debug
    - name: https-client-auth
      value: request
    # - name: fips-mode
    #   value: non-strict
    - name: spi-x509cert-lookup-provider
      value: awsalb
    # - name: spi-x509cert-lookup-awsalb-certificate-chain-length
    #   value: '10'
    # - name: spi-x509cert-lookup-awsalb-trust-proxy-verification
    #   value: 'false'
    - name: spi-x509cert-lookup-awsalb-ssl-client-cert
      value: X-Amzn-Mtls-Clientcert
  unsupported:
    podTemplate:
      metadata:
        labels:
          keycloak: keycloak-sentinel
      spec:
        initContainers:
          - name: pki-initialize
            image: registry.access.redhat.com/ubi9/openjdk-21:latest
            securityContext:
              privileged: false
              runAsUser: 0
              runAsGroup: 0
            command:
              - /bin/bash
              - "-c"
            args:
              - |
                set -e
                echo "Initializing PKI"
                ls -all /opt/scripts
                cat /opt/scripts/create_keystore_container.sh
                bash /opt/scripts/create_keystore_container.sh
                update-ca-trust extract
                trust list --filter ca-anchors | grep DOD -i -A 2 -B 3
                cp -ra /etc/pki/* /etc/pki-custom
                echo "Initializing PKI done"
            volumeMounts:
              - name: pki-custom-data
                mountPath: /etc/pki-custom
              - name: keycloak-tls-certificates
                mountPath: /etc/pki/ca-trust/source/anchors/ca.crt
                subPath: ca.crt
              - name: dod-ca-rhel
                mountPath: /opt/scripts/create_keystore_container.sh
                subPath: create_keystore_container.sh
        containers:
          - volumeMounts:
              - name: pki-custom-data
                mountPath: /etc/pki
              - name: keycloak-conf
                mountPath: /opt/keycloak/conf/quarkus.properties
                subPath: quarkus.properties
              - name: keycloak-provider-plugins
                mountPath: /opt/keycloak/providers/keycloak-spi-awsalb-mtls.jar
                subPath: keycloak-spi-awsalb-mtls.jar
            args:
              - --debug
              - --verbose
              - start
        volumes:
          - name: pki-custom-data
            emptyDir: {}
          - name: keycloak-conf
            configMap:
              name: keycloak-conf
          - name: keycloak-provider-plugins
            configMap:
              name: keycloak-provider-plugins
          - name: dod-ca-rhel
            configMap:
              name: dod-ca-rhel
