repos:
  # SECURITY
  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.2"
    hooks:
      - id: bandit

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  # FORMATTING & MISC
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.0
    hooks:
      - id: codespell
        entry: bash -c 'codespell "$@" || true' -- # Don't block, just alert
        verbose: true

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        files: .*\.(ya?ml|json|md)$
        exclude: (?x)^(
          .pre-commit-config.yaml|
          mkdocs.yml|
          )$

  # PYTHON FORMATTING
  - repo: https://github.com/ambv/black
    rev: "24.10.0"
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: "7.1.1"
    hooks:
      - id: flake8
        args: ["--max-line-length=88"] # Same max-length as black

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.14.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        entry: bash -c 'mypy "$@" || true' -- # Don't block, just alert
        verbose: true

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.8.0
  #   hooks:
  #     - id: isort
  #       name: isort (python)

  # CFN CHECKS & LINTING
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v1.22.7 # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: .*\.(ya?ml)$
        exclude: (?x)^(
          .pre-commit-config.yaml|
          mkdocs.yml|
          .gitlab-ci.yml|
          )$

  #- repo: https://github.com/stelligent/cfn_nag
  #  rev: "v0.8.10"
  #  hooks:
  #    - id: cfn-nag
  #      files: .*\.(ya?ml|json)$
  #      exclude: (?x)^(
  #        .pre-commit-config.yaml|
  #        .gitlab-ci.yml|
  #        mkdocs.yml|
  #        workspaces-automation.app.sample.cdk.json|
  #        cdk.json|
  #        )$

  # Legal Text
  # - repo: https://github.com/dontirun/text-prepender
  #   rev: v0.1.0
  #   hooks:
  #   - id: text-prepender
  #     exclude: (?x)^(
  #         requirements.txt|
  #         requirements-dev.txt|
  #         )$
  #     # args:
  #     #   - '--text-file'
  #     #   - 'NOTICE'
