# Source: nifikop/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifikops
  namespace: nifikops
  labels:
    app: nifikop
    chart: nifikop-1.13.0
    heritage: Helm
    operator: nifi
    release: nifikops
    control-plane: nifikop

  annotations:

spec:
  selector:
    matchLabels:
      control-plane: nifikop
      name: nifikop
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: nifikop
        name: nifikop
        app: nifikop
        operator: nifi
        release: nifikops    
    
      annotations:    
    
    spec:
      serviceAccountName: nifikop
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: nifikop-webhook-server-cert
      securityContext:
        runAsUser: 1000
      containers:
        - command:
            - /manager
          args:
            - -metrics-bind-address=:9090
            - -leader-elect
            - -cert-manager-enabled=true
            - -webhook-enabled=true
          image: "ghcr.io/konpyutaika/docker-images/nifikop:v1.13.0-release"
          imagePullPolicy: "Always"
          name: nifikop
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: WATCH_NAMESPACE
              value: nifi,nifikops
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nifikop"
            - name: LOG_LEVEL
              value: Debug
            - name: LOG_ENCODING
              value: json
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
      terminationGracePeriodSeconds: 10
