environment:
  name: dev
  region: us-gov-west-1
  account: "303344244756"

hostedZones: &hostedZones
  - zoneName: denali.jktruong.people.aws.dev
    private: true
    vpc:
      id: &vpcId vpc-0a1b3d9e9e45c96ab

clusters:
  - name: SharedServices
    version: "1.30"
    vpc:
      id: *vpcId
      subnets:
        - id: subnet-0d2bfe25aa0f19aed
        - id: subnet-07f068c8e23af23e2
    hostedZones: *hostedZones
    nodeGroups:
      - name: general
        instanceType: t3a.xlarge
        ami: &ami
          name: amazon-eks-node-1.30-*
        storage: &storage
          rootDeviceName: /dev/xvda
          sizeInGB: 20
          type: gp3
        subnets:
          - id: subnet-0d2bfe25aa0f19aed
          - id: subnet-07f068c8e23af23e2
        desiredCapacity: 2
        maxSize: 10
