Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Parameters
        Parameters:
          - IamPrefix
          - ResourceSuffix
          - VpcId
          - VpcCidr
          - PrivateSubnetIds
          - LambdaStorageBucket

      - Label:
          default: Logging Stack Parameters
        Parameters:
          - TemplateURLLoggingStack

      - Label:
          default: Ingest Stack Parameters
        Parameters:
          - TemplateURLIngestStack
          - IngestStackObjectTaggerLambdaCodeKey
          - IngestStackApiGwLambdaCodeKey
          - IngestStackBucket1CDSProfile
          - IngestStackBucket2CDSProfile
          - IngestStackBucketOneGovPoc
          - IngestStackBucketOneDataOwner
          - IngestStackBucketOneKeyOwner
          - IngestStackBucketTwoGovPoc
          - IngestStackBucketTwoDataOwner
          - IngestStackBucketTwoKeyOwner

      - Label:
          default: Pipeline Stack Parameters
        Parameters:
          - TemplateURLPipelineStack
          - PipelineStackDiodeAccountId
          - PipelineStackPipelineAmiId
          - PipelineStackApprovedFileTypes
          - PipelineStackDfdlApprovedFileTypes
          - PipelineStackTransferResultLambdaCodeKey
          - PipelineStackDiodeSimulatorInstanceRole

      - Label:
          default: STFP Stack Parameters
        Parameters:
          - TemplateURLSftpServerStack
          - SftpServerStackSftpUserName
          - SftpServerStackSftpServerSubnetIds
          - SftpServerStackSftpBucketCDSProfile
          - SftpServerStackSftpBucketDataOwner
          - SftpServerStackSftpBucketGovPoc
          - SftpServerStackSftpBucketKeyOwner

    ParameterLabels:
      IamPrefix:
        default: IAM Prefix
      ResourceSuffix:
        default: Resource Suffix
      VpcId:
        default: VPC ID
      VpcCidr:
        default: VPC CIDR
      PrivateSubnetIds:
        default: Private Subnet IDs within the VPC
      LambdaStorageBucket:
        default: Lambda Storage Bucket

      TemplateURLLoggingStack:
        default: Logging Stack Template URL

      TemplateURLIngestStack:
        default: Ingest Stack Template URL
      IngestStackObjectTaggerLambdaCodeKey:
        default: Ingest Stack Object Tagger Lambda Code Key
      IngestStackApiGwLambdaCodeKey:
        default: Ingest Stack API Gateway Lambda Code Key
      IngestStackBucket1CDSProfile:
        default: Ingest Stack Bucket 1 CDS Profile
      IngestStackBucket2CDSProfile:
        default: Ingest Stack Bucket 2 CDS Profile
      IngestStackBucketOneGovPoc:
        default: Ingest Stack Bucket One Gov POC
      IngestStackBucketOneDataOwner:
        default: Pipeline Stack Bucket One Data Owner
      IngestStackBucketOneKeyOwner:
        default: Pipeline Stack Bucket One Key Owner
      IngestStackBucketTwoGovPoc:
        default: Pipeline Stack Bucket Two Gov POC
      IngestStackBucketTwoDataOwner:
        default: Pipeline Stack Bucket Two Data Owner
      IngestStackBucketTwoKeyOwner:
        default: Pipeline Stack Bucket Two Key Owner

      TemplateURLPipelineStack:
        default: Pipeline Stack Template URL
      PipelineStackTransferResultLambdaCodeKey:
        default: Pipeline Stack Transfer Result Lambda Code Key
      PipelineStackDiodeSimulatorInstanceRole:
        default: Pipeline Stack Diode Simulator Instance Role
      PipelineStackPipelineAmiId:
        default: Pipeline Stack Pipeline AMI ID
      PipelineStackApprovedFileTypes:
        default: Approved File Types
      PipelineStackDfdlApprovedFileTypes:
        default: DFDL Approved File Types
      PipelineStackDiodeAccountId:
        default: Pipeline Stack Diode Account ID

      TemplateURLSftpServerStack:
        default: SFTP Server Stack Template URL
      SftpServerStackSftpUserName:
        default: SFTP Server Stack SFTP User Name
      SftpServerStackSftpServerSubnetIds:
        default: SFTP Server Stack SFTP Server Subnet IDs
      SftpServerStackSftpBucketCDSProfile:
        default: SFTP Server Stack SFTP Bucket CDS Profile
      SftpServerStackSftpBucketDataOwner:
        default: SFTP Server Stack SFTP Bucket Data Owner
      SftpServerStackSftpBucketGovPoc:
        default: SFTP Server Stack SFTP Bucket Gov POC
      SftpServerStackSftpBucketKeyOwner:
        default: SFTP Server Stack SFTP Bucket Key Owner

Parameters:
  IamPrefix:
    Type: String
    Description: Required prefix for IAM resources
    Default: AFC2S
    AllowedValues: [AFC2S]
    ConstraintDescription: Must be "AFC2S"

  ResourceSuffix:
    Type: String
    Description: >-
      Suffix added to the named AWS resources. It must start with a lowercase letter and contain
      only lowercase letters, numbers, and hyphens; its length cannot exceed 20.
    AllowedPattern: ^[a-z0-9-]{1,20}$
    ConstraintDescription: Must start with a lowercase letter and contain only lowercase letters, numbers, and hyphens; its length cannot exceed 20.

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

  VpcCidr:
    Type: String
    Description: The CIDR block of the VPC

  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The list of private subnet IDs to use for the pipeline

  LambdaStorageBucket:
    Type: String
    Description: Name of S3 bucket where the Lambda code is stored

  TemplateURLLoggingStack:
    Type: String
    Description: >
      S3 URL for Logging Stack.
      For example, https://<bucket-name>.s3.us-gov-west-1.amazonaws.com/aftac_logging_stack.yaml

  TemplateURLIngestStack:
    Type: String
    Description: >
      S3 URL for Ingest Stack.
      For example, https://<bucket-name>.s3.us-gov-west-1.amazonaws.com/aftac_ingest_stack.yaml

  IngestStackBucket1CDSProfile:
    Type: String
    Description: CDS Profile for Ingest Bucket 1
    AllowedValues: [CDS_1, CDS_2, CDS_3]
    ConstraintDescription: Must be CDS_1, CDS_2, or CDS_3

  IngestStackBucket2CDSProfile:
    Type: String
    Description: CDS Profile for Ingest Bucket 2
    AllowedValues: [CDS_1, CDS_2, CDS_3]
    ConstraintDescription: Must be CDS_1, CDS_2, or CDS_3

  IngestStackObjectTaggerLambdaCodeKey:
    Type: String
    Description: S3 key for the Object Tagger Lambda code
    Default: lambda_functions/object_tagger.zip

  IngestStackApiGwLambdaCodeKey:
    Type: String
    Description: S3 key for the API Gateway Lambda code
    Default: lambda_functions/presigner.zip

  IngestStackBucketOneGovPoc:
    Type: String
    Description: String to be added as a tag to objects in Bucket 1
    Default: Monica

  IngestStackBucketOneDataOwner:
    Type: String
    Description: String to be added as a tag to objects in Bucket 1
    Default: Phoebe

  IngestStackBucketOneKeyOwner:
    Type: String
    Description: String to be added as a tag to objects in Bucket 1
    Default: Chandler

  IngestStackBucketTwoGovPoc:
    Type: String
    Description: String to be added as a tag to objects in Bucket 2
    Default: Ross

  IngestStackBucketTwoDataOwner:
    Type: String
    Description: String to be added as a tag to objects in Bucket 2
    Default: Rachel

  IngestStackBucketTwoKeyOwner:
    Type: String
    Description: String to be added as a tag to objects in Bucket 2
    Default: Joey

  TemplateURLPipelineStack:
    Type: String
    Description: >
      S3 URL for Pipeline Stack.
      For example, https://<bucket-name>.s3.us-gov-west-1.amazonaws.com/aftac_pipeline_stack.yaml

  PipelineStackPipelineAmiId:
    Type: AWS::EC2::Image::Id
    Description: The AMI ID to use for the pipeline.

  PipelineStackTransferResultLambdaCodeKey:
    Type: String
    Description: The S3 key of the pipeline lambda code
    Default: lambda_functions/transfer_result.zip

  PipelineStackDiodeSimulatorInstanceRole:
    Type: String
    Description: >
      If using a Diode Simulator, the ARN of the role associated with the instance profile for the Diode Simulator instance.
      Otherwise, leave it blank.
    AllowedPattern: ^$|^arn:(aws|aws-us-gov):iam::\d{12}:role/.*

  PipelineStackDiodeAccountId:
    Type: String
    Description: Account ID for Diode Account
    AllowedPattern: ^\d{12}$
    ConstraintDescription: Must be a valid 12-digit AWS account ID

  PipelineStackApprovedFileTypes:
    Type: CommaDelimitedList
    Description: A comma-separated list of file types allowed through the validation pipeline
    Default: csv, flac, wav, mp4, txt, json, zip

  PipelineStackDfdlApprovedFileTypes:
    Type: CommaDelimitedList
    Description: A comma-separated list of file types allowed through the DFDL validation pipeline
    Default: infoset, xml

  TemplateURLSftpServerStack:
    Type: String
    Description: >
      S3 URL for SFTP Server Stack.
      For example, https://<bucket-name>.s3.us-gov-west-1.amazonaws.com/aftac_sftp_stack.yaml

  SftpServerStackSftpUserName:
    Type: String
    Description: Username for SFTP user
    Default: sftpuser

  SftpServerStackSftpServerSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Two (2) Subnet IDs for SFTP server

  SftpServerStackSftpBucketCDSProfile:
    Type: String
    Description: CDS Profile for SFTP Bucket
    AllowedValues: [CDS_1, CDS_2, CDS_3]
    ConstraintDescription: Must be CDS_1, CDS_2, or CDS_3

  SftpServerStackSftpBucketDataOwner:
    Type: String
    Description: Name of the Sftp Server Data Owner
    Default: George

  SftpServerStackSftpBucketGovPoc:
    Type: String
    Description: Name of the Sftp Server Gov Poc
    Default: Jerry

  SftpServerStackSftpBucketKeyOwner:
    Type: String
    Description: Name of the Sftp Server Key Owner
    Default: Cosmo

Resources:
  LoggingStack:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Ref TemplateURLLoggingStack
      Parameters:
        ResourceSuffix: !Ref ResourceSuffix

  IngestStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LoggingStack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Ref TemplateURLIngestStack
      Parameters:
        ResourceSuffix: !Ref ResourceSuffix
        VpcId: !Ref VpcId
        PrivateSubnetIds: !Join [",", !Ref PrivateSubnetIds]
        LambdaStorageBucket: !Ref LambdaStorageBucket
        ObjectTaggerLambdaCodeKey: !Ref IngestStackObjectTaggerLambdaCodeKey
        ApiGwLambdaCodeKey: !Ref IngestStackApiGwLambdaCodeKey
        Bucket1CDSProfile: !Ref IngestStackBucket1CDSProfile
        Bucket2CDSProfile: !Ref IngestStackBucket2CDSProfile
        BucketOneGovPoc: !Ref IngestStackBucketOneGovPoc
        BucketOneDataOwner: !Ref IngestStackBucketOneDataOwner
        BucketOneKeyOwner: !Ref IngestStackBucketOneKeyOwner
        BucketTwoGovPoc: !Ref IngestStackBucketTwoGovPoc
        BucketTwoDataOwner: !Ref IngestStackBucketTwoDataOwner
        BucketTwoKeyOwner: !Ref IngestStackBucketTwoKeyOwner
        ObjectTaggerRoleARN:
          Fn::ImportValue: !Sub ObjectTaggerRoleArn-${ResourceSuffix}
        PresignGeneratorServiceRole:
          Fn::ImportValue: !Sub PresignGeneratorServiceRoleArn-${ResourceSuffix}
        FileUploaderCloudWatchRole:
          Fn::ImportValue: !Sub FileUploaderCloudWatchRoleArn-${ResourceSuffix}
        APILambdaInvokeRole:
          Fn::ImportValue: !Sub APILambdaInvokeRoleArn-${ResourceSuffix}

  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IngestStack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Ref TemplateURLPipelineStack
      Parameters:
        IamPrefix: !Ref IamPrefix
        ResourceSuffix: !Ref ResourceSuffix
        VpcId: !Ref VpcId
        VpcCidr: !Ref VpcCidr
        PrivateSubnetIds: !Join [",", !Ref PrivateSubnetIds]
        LambdaStorageBucket: !Ref LambdaStorageBucket
        TransferResultLambdaCodeKey: !Ref PipelineStackTransferResultLambdaCodeKey
        ApprovedFileTypes: !Join [",", !Ref PipelineStackApprovedFileTypes]
        DfdlApprovedFileTypes:
          !Join [",", !Ref PipelineStackDfdlApprovedFileTypes]
        DiodeAccountId: !Ref PipelineStackDiodeAccountId
        PipelineAmiId: !Ref PipelineStackPipelineAmiId
        DiodeSimulatorInstanceRole: !Ref PipelineStackDiodeSimulatorInstanceRole
        TransferResultServiceRole:
          Fn::ImportValue: !Sub TransferResultLambdaRoleArn-${ResourceSuffix}
        Ec2ScannerInstanceProfileARN:
          Fn::ImportValue: !Sub Ec2ScannerInstanceProfile-${ResourceSuffix}

  SftpServerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: PipelineStack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Ref TemplateURLSftpServerStack
      Parameters:
        ResourceSuffix: !Ref ResourceSuffix
        VpcId: !Ref VpcId
        PrivateSubnetIds: !Join [",", !Ref PrivateSubnetIds]
        SftpServerSubnetIds:
          !Join [",", !Ref SftpServerStackSftpServerSubnetIds]
        LambdaStorageBucket: !Ref LambdaStorageBucket
        ObjectTaggerLambdaCodeKey: !Ref IngestStackObjectTaggerLambdaCodeKey
        SftpUserName: !Ref SftpServerStackSftpUserName
        SftpBucketCDSProfile: !Ref SftpServerStackSftpBucketCDSProfile
        SftpBucketDataOwner: !Ref SftpServerStackSftpBucketDataOwner
        SftpBucketGovPoc: !Ref SftpServerStackSftpBucketGovPoc
        SftpBucketKeyOwner: !Ref SftpServerStackSftpBucketKeyOwner
        TransferUserRoleArn:
          Fn::ImportValue: !Sub TransferUserRoleArn-${ResourceSuffix}
        TransferLoggingRoleArn:
          Fn::ImportValue: !Sub TransferLoggingRoleArn-${ResourceSuffix}
        ObjectTaggerRoleARN:
          Fn::ImportValue: !Sub ObjectTaggerRoleArn-${ResourceSuffix}
