Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Parameters
        Parameters:
          - IamPrefix
          - ResourceSuffix
          - PermissionsBoundaryPolicyArn
          - VpcId
          - VpcCidr
          - PrivateSubnetIds
          - S3PrefixListId
          - DDBPrefixListId

      - Label:
          default: Logging Stack Parameters
        Parameters:
          - TemplateURLLoggingStack

      - Label:
          default: Ingest Stack Parameters
        Parameters:
          - TemplateURLIngestStack

      - Label:
          default: Pipeline Stack Parameters
        Parameters:
          - TemplateURLPipelineStack
          - PipelineStackDiodeAccountId
          - PipelineStackPipelineAmiId
          - PipelineStackApprovedFileTypes
          - PipelineStackDfdlApprovedFileTypes
          - PipelineStackDiodeSimulatorInstanceRole

      - Label:
          default: STFP Stack Parameters
        Parameters:
          - TemplateURLSftpServerStack
          - SftpServerStackSftpServerSubnetIds
          - SftpServerIngressRuleCIDR

    ParameterLabels:
      IamPrefix:
        default: IAM Prefix
      ResourceSuffix:
        default: Resource Suffix
      PermissionsBoundaryPolicyArn:
        default: Permissions Boundary Policy ARN
      VpcId:
        default: VPC ID
      VpcCidr:
        default: VPC CIDR
      PrivateSubnetIds:
        default: Private Subnet IDs within the VPC
      S3PrefixListId:
        default: S3 Prefix List ID
      DDBPrefixListId:
        default: DynamoDB Prefix List ID

      TemplateURLLoggingStack:
        default: Logging Stack Template URL

      TemplateURLIngestStack:
        default: Ingest Stack Template URL

      TemplateURLPipelineStack:
        default: Pipeline Stack Template URL
      PipelineStackDiodeSimulatorInstanceRole:
        default: Pipeline Stack Diode Simulator Instance Role
      PipelineStackPipelineAmiId:
        default: Pipeline Stack Pipeline AMI ID
      PipelineStackApprovedFileTypes:
        default: Approved File Types
      PipelineStackDfdlApprovedFileTypes:
        default: DFDL Approved File Types
      PipelineStackDiodeAccountId:
        default: Pipeline Stack Diode Account ID

      TemplateURLSftpServerStack:
        default: SFTP Server Stack Template URL
      SftpServerStackSftpServerSubnetIds:
        default: SFTP Server Stack SFTP Server Subnet IDs
      SftpServerIngressRuleCIDR:
        default: SFTP Server Stack Ingress Rule CIDR

Parameters:
  IamPrefix:
    Type: String
    Description: Required prefix for IAM resources
    Default: AFC2S
    AllowedValues: [AFC2S]
    ConstraintDescription: Must be "AFC2S"

  ResourceSuffix:
    Type: String
    Description: >-
      Suffix added to the named AWS resources. It must start with a lowercase letter and contain
      only lowercase letters, numbers, and hyphens; its length cannot exceed 20.
    AllowedPattern: ^[a-z0-9-]{1,20}$
    ConstraintDescription: Must start with a lowercase letter and contain only lowercase letters, numbers, and hyphens; its length cannot exceed 20.

  PermissionsBoundaryPolicyArn:
    Type: String
    Description: ARN of the policy that is used to set the permissions boundary for IAM resources
    AllowedPattern: ^arn:(aws|aws-us-gov):iam::(\d{12}|aws):policy/.*
    ConstraintDescription: Must be a valid IAM policy ARN

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

  VpcCidr:
    Type: String
    Description: The CIDR block of the VPC

  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The list of private subnet IDs to use for the pipeline

  S3PrefixListId:
    Type: String
    Description: S3 Prefix List ID (e.g. pl-7a3a1b0f)
    AllowedPattern: ^pl-([a-f0-9]{8}|[a-f0-9]{17})$
    ConstraintDescription: Must be a valid S3 Prefix List ID

  DDBPrefixListId:
    Type: String
    Description: DynamoDB Prefix List ID (e.g. pl-1b4c2f9e)
    AllowedPattern: ^pl-([a-f0-9]{8}|[a-f0-9]{17})$
    ConstraintDescription: Must be a valid DynamoDB Prefix List ID

  TemplateURLLoggingStack:
    Type: String
    Description: >
      S3 URL for Logging Stack.
      For example, https://<bucket-name>.s3.us-gov-west-1.amazonaws.com/aftac_logging_stack.yaml

  TemplateURLIngestStack:
    Type: String
    Description: >
      S3 URL for Ingest Stack.
      For example, https://<bucket-name>.s3.us-gov-west-1.amazonaws.com/aftac_ingest_stack.yaml

  TemplateURLPipelineStack:
    Type: String
    Description: >
      S3 URL for Pipeline Stack.
      For example, https://<bucket-name>.s3.us-gov-west-1.amazonaws.com/aftac_pipeline_stack.yaml

  PipelineStackPipelineAmiId:
    Type: AWS::EC2::Image::Id
    Description: The AMI ID to use for the pipeline.

  PipelineStackDiodeSimulatorInstanceRole:
    Type: String
    Description: >
      If using a Diode Simulator, the ARN of the role associated with the instance profile for the Diode Simulator instance.
      Otherwise, leave it blank.
    AllowedPattern: ^$|^arn:(aws|aws-us-gov):iam::\d{12}:role/.*

  PipelineStackDiodeAccountId:
    Type: String
    Description: Account ID for Diode Account
    AllowedPattern: ^\d{12}$
    ConstraintDescription: Must be a valid 12-digit AWS account ID

  PipelineStackApprovedFileTypes:
    Type: CommaDelimitedList
    Description: A comma-separated list of file types allowed through the validation pipeline
    Default: csv, flac, wav, mp4, txt, json, zip

  PipelineStackDfdlApprovedFileTypes:
    Type: CommaDelimitedList
    Description: A comma-separated list of file types allowed through the DFDL validation pipeline
    Default: infoset, xml

  TemplateURLSftpServerStack:
    Type: String
    Description: >
      S3 URL for SFTP Server Stack.
      For example, https://<bucket-name>.s3.us-gov-west-1.amazonaws.com/aftac_sftp_stack.yaml

  SftpServerStackSftpServerSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Two (2) Subnet IDs for SFTP server

  SftpServerIngressRuleCIDR:
    Type: String
    Description: CIDR block for SFTP server ingress rule
    Default: 0.0.0.0/0
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid CIDR block

Resources:
  LoggingStack:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Ref TemplateURLLoggingStack
      Parameters:
        ResourceSuffix: !Ref ResourceSuffix

  IngestStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LoggingStack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Ref TemplateURLIngestStack
      Parameters:
        IamPrefix: !Ref IamPrefix
        ResourceSuffix: !Ref ResourceSuffix
        PermissionsBoundaryPolicyArn: !Ref PermissionsBoundaryPolicyArn
        VpcId: !Ref VpcId
        PrivateSubnetIds: !Join [",", !Ref PrivateSubnetIds]
        VpcCidr: !Ref VpcCidr
        S3PrefixListId: !Ref S3PrefixListId

  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IngestStack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Ref TemplateURLPipelineStack
      Parameters:
        IamPrefix: !Ref IamPrefix
        ResourceSuffix: !Ref ResourceSuffix
        PermissionsBoundaryPolicyArn: !Ref PermissionsBoundaryPolicyArn
        VpcId: !Ref VpcId
        VpcCidr: !Ref VpcCidr
        PrivateSubnetIds: !Join [",", !Ref PrivateSubnetIds]
        S3PrefixListId: !Ref S3PrefixListId
        DDBPrefixListId: !Ref DDBPrefixListId
        ApprovedFileTypes: !Join [",", !Ref PipelineStackApprovedFileTypes]
        DfdlApprovedFileTypes:
          !Join [",", !Ref PipelineStackDfdlApprovedFileTypes]
        DiodeAccountId: !Ref PipelineStackDiodeAccountId
        PipelineAmiId: !Ref PipelineStackPipelineAmiId
        DiodeSimulatorInstanceRole: !Ref PipelineStackDiodeSimulatorInstanceRole

  SftpServerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: PipelineStack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Ref TemplateURLSftpServerStack
      Parameters:
        IamPrefix: !Ref IamPrefix
        ResourceSuffix: !Ref ResourceSuffix
        PermissionsBoundaryPolicyArn: !Ref PermissionsBoundaryPolicyArn
        VpcId: !Ref VpcId
        VpcCidr: !Ref VpcCidr
        S3PrefixListId: !Ref S3PrefixListId
        SftpServerSubnetIds:
          !Join [",", !Ref SftpServerStackSftpServerSubnetIds]
        SftpServerIngressRuleCIDR: !Ref SftpServerIngressRuleCIDR
