Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General
        Parameters:
          - ResourceSuffix

      - Label:
          default: Tags
        Parameters:
          - IngestBucketMappingId
          - IngestBucketDestinationBucket
          - IngestBucketDataOwner
          - IngestBucketDataSteward
          - IngestBucketGovPoc
          - IngestBucketKeyOwner

      - Label:
          default: (OPTIONAL) Bucket Policy
        Parameters:
          - AllowedRoleArn

      - Label:
          default: (OPTIONAL) SFTP
        Parameters:
          - SftpUserName
          - SshPublicKeys

      - Label:
          default: Bucket LifeCycle Configuration
        Parameters:
          - ObjectExpirationInDays

    ParameterLabels:
      ResourceSuffix:
        default: Resource Suffix
      IngestBucketMappingId:
        default: (Conditional) Mapping ID
      IngestBucketDestinationBucket:
        default: (Conditional) Destination Bucket Name
      IngestBucketDataOwner:
        default: Data Owner
      IngestBucketDataSteward:
        default: Data Steward
      IngestBucketGovPoc:
        default: GOV POC
      IngestBucketKeyOwner:
        default: Key Owner
      AllowedRoleArn:
        default: Allowed Role ARN
      SftpUserName:
        default: SFTP User Name
      SshPublicKeys:
        default: SSH Public Keys
      ObjectExpirationInDays:
        default: Object Expiration In Days

Parameters:
  ResourceSuffix:
    Type: String
    Description: >-
      (Required) Suffix added to the named AWS resources. It must start with a lowercase letter and contain
      only lowercase letters, numbers, and hyphens; its length cannot exceed 20.
    AllowedPattern: ^[a-z0-9-]{1,20}$
    ConstraintDescription: Must start with a lowercase letter and contain only lowercase letters, numbers, and hyphens; its length cannot exceed 20.

  IngestBucketMappingId:
    Type: String
    Description: (Conditional) Value for tag key MappingId. Do not specify a value here if you specify a value in Destination Bucket Name.
    Default: 12346789-abcd-1234-abcd-123456789012
    AllowedPattern: ^$|^[a-f0-9]{8}-([a-f0-9]{4}-){3}[a-f0-9]{12}$
    ConstraintDescription: Must be a valid Mapping ID

  IngestBucketDestinationBucket:
    Type: String
    Description: (Conditional) Value for tag key DestinationBucket. Do not specify a value here if you specify a value in Mapping ID.
    AllowedPattern: ^$|^(?!\s*arn:)\S+$
    ConstraintDescription: Must be a valid bucket name

  IngestBucketDataOwner:
    Type: String
    Description: (Required) Value for tag key DataOwner
    AllowedPattern: (?!.*/).+
    ConstraintDescription: Must have at least one valid character and not contain a slash (/)

  IngestBucketDataSteward:
    Type: String
    Description: (Required) Value for tag key DataSteward
    AllowedPattern: (?!.*/).+
    ConstraintDescription: Must have at least one valid character and not contain a slash (/)

  IngestBucketGovPoc:
    Type: String
    Description: (Required) Value for tag key GovPOC
    AllowedPattern: (?!.*/).+
    ConstraintDescription: Must have at least one valid character and not contain a slash (/)

  IngestBucketKeyOwner:
    Type: String
    Description: (Required) Value for tag key KeyOwner
    AllowedPattern: (?!.*/).+
    ConstraintDescription: Must have at least one valid character and not contain a slash (/)

  AllowedRoleArn:
    Type: String
    Description: (Optional) ARN of the role that is allowed to write to the ingestion bucket
    AllowedPattern: ^$|^arn:(aws|aws-us-gov):iam::\d{12}:role/\S+
    ConstraintDescription: Must start with 'arn:' and be composed of lowercase letters, numbers, and hyphens; it cannot exceed 1024 characters.

  SftpUserName:
    Type: String
    Description: Username for SFTP user who is allowed to write to the ingestion bucket via SFTP
    AllowedPattern: ^$|^(?![-.@].*)[a-zA-Z0-9-_.@]{3,100}$
    ConstraintDescription: >-
      Username must be a minimum of 3 and a maximum of 100 characters long.
      The following are valid characters: a-z, A-Z, 0-9, underscore '_', hyphen '-', period '.', and at sign '@'.
      The user name can't start with a hyphen, period, or at sign.

  SshPublicKeys:
    Type: CommaDelimitedList
    Description: >-
      Public key portion of the SSH keys stored for the SFTP user. If adding more than one, separate them with a comma.
      If you want to delete the key(s), clear out the contents from this field.

  ObjectExpirationInDays:
    Type: Number
    Description: Enter the number of days you want to keep objects in the Ingestion Bucket.
    Default: 365

Rules:
  MappingIdOnly:
    RuleCondition: !Not [!Equals [!Ref IngestBucketMappingId, ""]]
    Assertions:
      - Assert: !Equals [!Ref IngestBucketDestinationBucket, ""]
        AssertDescription: You cannot specify a value in both Mapping ID and Destination Bucket Name
  DestinationBucketOnly:
    RuleCondition: !Not [!Equals [!Ref IngestBucketDestinationBucket, ""]]
    Assertions:
      - Assert: !Equals [!Ref IngestBucketMappingId, ""]
        AssertDescription: You cannot specify a value in both Mapping ID and Destination Bucket Name

Conditions:
  CreateSftpUser: !Not [!Equals [!Ref SftpUserName, ""]]
  SshPublicKeyProvided: !Not [!Equals [!Join ["", !Ref SshPublicKeys], ""]]
  UseMappingId: !Not [!Equals [!Ref IngestBucketMappingId, ""]]
  UseDestinationBucket: !Not [!Equals [!Ref IngestBucketDestinationBucket, ""]]
  UseAllowedRoleArn: !Not [!Equals [!Ref AllowedRoleArn, ""]]

Resources:
  IngestBucket:
    Type: AWS::S3::Bucket
    Properties:
      LoggingConfiguration:
        DestinationBucketName:
          Fn::ImportValue: !Sub access-logs-bucket-${ResourceSuffix}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function:
              Fn::ImportValue: !Sub aftac-pipeline-object-tagger-${ResourceSuffix}
      LifecycleConfiguration:
        Rules:
          - Id: LifeCycleRule-1
            Status: Enabled
            ExpirationInDays: !Ref ObjectExpirationInDays
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
      Tags:
        - !If
          - UseMappingId
          - Key: MappingId
            Value: !Ref IngestBucketMappingId
          - !Ref AWS::NoValue
        - !If
          - UseDestinationBucket
          - Key: IngestBucketDestinationBucket
            Value: !Ref IngestBucketDestinationBucket
          - !Ref AWS::NoValue
        - Key: DataOwner
          Value: !Ref IngestBucketDataOwner
        - Key: DataSteward
          Value: !Ref IngestBucketDataSteward
        - Key: GovPOC
          Value: !Ref IngestBucketGovPoc
        - Key: KeyOwner
          Value: !Ref IngestBucketKeyOwner

  IngestBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref IngestBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Principal:
              AWS: "*"
            Action: s3:*
            Resource:
              - !Sub ${IngestBucket.Arn}
              - !Sub ${IngestBucket.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: false
          - !If
            - UseAllowedRoleArn
            - Effect: Allow
              Principal:
                AWS: !Ref AllowedRoleArn
              Action: s3:PutObject
              Resource: !Sub ${IngestBucket.Arn}/*
            - !Ref AWS::NoValue

  TransferUser:
    Type: AWS::Transfer::User
    Condition: CreateSftpUser
    Properties:
      ServerId:
        Fn::ImportValue: !Sub SFTPServerId-${ResourceSuffix}
      Role:
        Fn::ImportValue: !Sub TransferUserRoleArn-${ResourceSuffix}
      UserName: !Ref SftpUserName
      HomeDirectoryType: LOGICAL
      HomeDirectoryMappings:
        - Entry: / # chroot
          Target: !Sub /${IngestBucket}/${SftpUserName} # Limit visibility to this directory (and below) only
          Type: DIRECTORY
      SshPublicKeys: !If
        - SshPublicKeyProvided
        - !Ref SshPublicKeys
        - []
