AWSTemplateFormatVersion: 2010-09-09
Description: This stack consists of VPC Endpoints and other resources

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: ""
        Parameters:
          - VpcId
          - ExistingVpcCidr
          - PrivateSubnetIds
          - PrivateRouteTableIds

    ParameterLabels:
      VpcId:
        default: VPC ID
      PrivateRouteTableIds:
        default: Private Route Table IDs
      PrivateSubnetIds:
        default: Private Subnet IDs
      ExistingVpcCidr:
        default: Existing VPC CIDR

Parameters:
  VpcId:
    Type: String
    Description: VPC ID for AFTAC VPC
    Default: vpc-048daa85d41f50b10
    AllowedPattern: ^vpc-([a-f0-9]{8}|[a-f0-9]{17})$
    ConstraintDescription: Must be a valid VPC ID.

  PrivateRouteTableIds:
    Type: CommaDelimitedList
    Description: Private Route Table IDs for AFTAC VPC
    Default: rtb-07027991a9dbb1f36
    AllowedPattern: ^rtb-([a-f0-9]{8}|[a-f0-9]{17})$
    ConstraintDescription: Must be one or more valid route table IDs.

  PrivateSubnetIds:
    Type: CommaDelimitedList
    Description: Private Subnet IDs for AFTAC VPC
    Default: subnet-0f2d694defec254c9, subnet-0f64b1f3ba14fd6ee, subnet-0e44f6353b9e3ee92
    AllowedPattern: ^subnet-([a-f0-9]{8}|[a-f0-9]{17})$
    ConstraintDescription: Must be one or more valid subnet IDs.

  ExistingVpcCidr:
    Type: String
    Description: CIDR of existing VPC
    Default: 10.162.208.0/20

Resources:
  privateVpcDynamoDbEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds: !Ref PrivateRouteTableIds
      ServiceName: !Sub com.amazonaws.${AWS::Region}.dynamodb
      VpcEndpointType: Gateway
      VpcId: !Ref VpcId

  VpcEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for VPC Endpoints
      SecurityGroupEgress:
        - CidrIp: 127.0.0.1/32
          Description: No outbound traffic allowed
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: !Ref ExistingVpcCidr
          Description: Allows inbound HTTPS traffic
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      VpcId: !Ref VpcId

  SsmVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !GetAtt VpcEndpointSecurityGroup.GroupId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      SubnetIds: !Ref PrivateSubnetIds
      VpcEndpointType: Interface
      VpcId: !Ref VpcId

  SsmMessagesVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !GetAtt VpcEndpointSecurityGroup.GroupId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      SubnetIds: !Ref PrivateSubnetIds
      VpcEndpointType: Interface
      VpcId: !Ref VpcId

  Ec2MessagesVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !GetAtt VpcEndpointSecurityGroup.GroupId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      SubnetIds: !Ref PrivateSubnetIds
      VpcEndpointType: Interface
      VpcId: !Ref VpcId

  SqsVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !GetAtt VpcEndpointSecurityGroup.GroupId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.sqs
      SubnetIds: !Ref PrivateSubnetIds
      VpcEndpointType: Interface
      VpcId: !Ref VpcId

  LogsVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !GetAtt VpcEndpointSecurityGroup.GroupId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      SubnetIds: !Ref PrivateSubnetIds
      VpcEndpointType: Interface
      VpcId: !Ref VpcId

  SnsVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !GetAtt VpcEndpointSecurityGroup.GroupId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.sns
      SubnetIds: !Ref PrivateSubnetIds
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
