Parameters:
  ResourceSuffix:
    Type: String
    Description: Suffix added to the named AWS resources

Resources:
  LogBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule:
          DefaultRetention:
            Days: 2555
            Mode: GOVERNANCE
      ObjectLockEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  LogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !Sub ${LogBucket.Arn}
              - !Sub ${LogBucket.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: false
          - Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
                - delivery.logs.amazonaws.com
            Action:
              - s3:GetBucketAcl
              - s3:ListBucket
              - s3:PutObject
            Resource:
              - !Sub ${LogBucket.Arn}
              - !Sub ${LogBucket.Arn}/*

  SftpServerLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      RetentionInDays: 731

  ApiGatewayStageLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      RetentionInDays: 731

  IngestWACLAccessLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      RetentionInDays: 731

Outputs:
  LogBucketExport:
    Description: Name of the S3 Logging Bucket
    Value: !Ref LogBucket

  SftpServerLogGroupExport:
    Description: ARN of the SFTP Server Log Group
    Value: !GetAtt SftpServerLogGroup.Arn
    Export:
      Name: !Sub aftac-pipeline-SftpServerLogGroup-${ResourceSuffix}

  ApiGatewayStageLogGroupARNExport:
    Description: Name of the API Gateway Stage Log Group
    Value: !GetAtt ApiGatewayStageLogGroup.Arn
    Export:
      Name: !Sub aftac-pipeline-ApiGatewayStageLogGroup-${ResourceSuffix}

  IngestWACLAccessLogGroupExport:
    Description: Name of the Ingest WACL Access Log Group
    Value: !Ref IngestWACLAccessLogGroup
    Export:
      Name: !Sub aftac-pipeline-IngestWACLAccessLogGroup-${ResourceSuffix}
