Parameters:
  IamPrefix:
    Type: String
    Description: Prefix added to all IAM resources

  PermissionsBoundaryPolicyArn:
    Type: String
    Description: ARN of the policy that is used to set the permissions boundary for IAM resources

  ResourceSuffix:
    Type: String
    Description: Suffix added to the named AWS resources

  VpcId:
    Type: String
    Description: VPC ID

  SftpServerSubnetIds:
    Type: CommaDelimitedList
    Description: Subnet IDs for SFTP server

  SftpServerIngressRuleCIDR:
    Type: String
    Description: CIDR for SFTP Server Ingress Rule

Resources:
  TransferLoggingRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      RoleName: !Sub ${IamPrefix}-TransferLoggingRole-${ResourceSuffix}
      PermissionsBoundary: !Ref PermissionsBoundaryPolicyArn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: transfer.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
      Policies:
        - PolicyName: TransferLoggingPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetBucketAcl
                  - s3:PutBucketAcl
                Resource: !Sub arn:${AWS::Partition}:s3:::*
        - PolicyName: AWSTransferLoggingAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*

  TransferUserRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      RoleName: !Sub ${IamPrefix}-TransferUserRole-${ResourceSuffix}
      PermissionsBoundary: !Ref PermissionsBoundaryPolicyArn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: transfer.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TransferUserPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetBucketAcl
                  - s3:PutBucketAcl
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObjectVersion
                  - s3:DeleteObjectVersion
                  - s3:ListBucket
                  - s3:DeleteObject
                  - s3:GetBucketLocation
                Resource: !Sub arn:${AWS::Partition}:s3:::*

  SftpServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for SFTP Server
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 127.0.0.1/32
          Description: Removes default egress rule that allows all egress traffic on all ports and IP protocols to any location
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SftpServerIngressRuleCIDR
          Description: Allow SSH access

  ElasticIpOne:
    Type: AWS::EC2::EIP

  ElasticIpTwo:
    Type: AWS::EC2::EIP

  SftpServerLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      RetentionInDays: 731

  SftpServer:
    Type: AWS::Transfer::Server
    Properties:
      Domain: S3
      EndpointType: VPC
      EndpointDetails:
        SecurityGroupIds:
          - !Ref SftpServerSecurityGroup
        SubnetIds: !Ref SftpServerSubnetIds
        AddressAllocationIds: # Must match the length of the list of subnet ids)
          - !GetAtt ElasticIpOne.AllocationId
          - !GetAtt ElasticIpTwo.AllocationId
        VpcId: !Ref VpcId
      IdentityProviderType: SERVICE_MANAGED
      Protocols:
        - SFTP
      ProtocolDetails:
        SetStatOption: ENABLE_NO_OP
      SecurityPolicyName: TransferSecurityPolicy-2024-01
      LoggingRole: !GetAtt TransferLoggingRole.Arn
      StructuredLogDestinations:
        - !GetAtt SftpServerLogGroup.Arn
      Tags:
        - Key: Name
          Value: !Sub SFTP-Server-${ResourceSuffix}

Outputs:
  SFTPServerId:
    Description: SFTP Server ID
    Value: !GetAtt SftpServer.ServerId
    Export:
      Name: !Sub SFTPServerId-${ResourceSuffix}

  TransferUserRole:
    Description: ARN of the Transfer User Role
    Value: !GetAtt TransferUserRole.Arn
    Export:
      Name: !Sub TransferUserRoleArn-${ResourceSuffix}
