Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Parameters
        Parameters:
          - pIamPrefix
          - pResourceSuffix
          - pPermissionsBoundaryPolicyArn

    ParameterLabels:
      pIamPrefix:
        default: IAM Prefix
      pResourceSuffix:
        default: Resource Suffix
      pPermissionsBoundaryPolicyArn:
        default: Permissions Boundary Policy ARN

Parameters:
  pIamPrefix:
    Type: String
    Description: Required prefix for IAM resources
    Default: AFC2S
    AllowedValues: [AFC2S]
    ConstraintDescription: Must be "AFC2S"

  pResourceSuffix:
    Type: String
    Description: >-
      Suffix added to the named AWS resources. It must start with a lowercase letter and contain
      only lowercase letters, numbers, and hyphens; its length cannot exceed 20.
    AllowedPattern: ^[a-z][a-z0-9-]{0,19}$
    ConstraintDescription: Must start with a lowercase letter and contain only lowercase letters, numbers, and hyphens; its length cannot exceed 20.

  pPermissionsBoundaryPolicyArn:
    Type: String
    Description: ARN of the policy that is used to set the permissions boundary for IAM resources
    AllowedPattern: ^arn:(aws|aws-us-gov):iam::(\d{12}|aws):policy/.*
    ConstraintDescription: Must be a valid IAM policy ARN

Resources:
  Ec2ScannerCwLogsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      ManagedPolicyName: !Sub ${pIamPrefix}-Ec2ScannerCwLogsPolicy-${pResourceSuffix}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogStreams
              - logs:PutLogEvents
              - logs:PutRetentionPolicy
              - cloudwatch:PutMetricData
            Effect: Allow
            Resource: "*"

  Ec2ScannerSqsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      ManagedPolicyName: !Sub ${pIamPrefix}-Ec2ScannerSqsPolicy-${pResourceSuffix}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sqs:DeleteMessage
              - sqs:ReceiveMessage
              - sqs:SendMessage
            Resource: !Sub arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:*

  Ec2ScannerS3Policy:
    Type: AWS::IAM::ManagedPolicy
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      ManagedPolicyName: !Sub ${pIamPrefix}-Ec2ScannerS3Policy-${pResourceSuffix}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:DeleteObject
              - s3:GetBucketAcl
              - s3:GetObject
              - s3:GetObjectTagging
              - s3:ListBucket
              - s3:PutObject
              - s3:PutObjectTagging
            Resource: "*"

  Ec2ScannerSnsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      ManagedPolicyName: !Sub ${pIamPrefix}-Ec2ScannerSnsPolicy-${pResourceSuffix}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sns:Publish
            Resource: "*"

  Ec2ScannerEc2Policy:
    Type: AWS::IAM::ManagedPolicy
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      ManagedPolicyName: !Sub ${pIamPrefix}-Ec2ScannerEc2Policy-${pResourceSuffix}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: ec2:DescribeTags
            Resource: "*"

  Ec2ScannerRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      RoleName: !Sub ${pIamPrefix}-Ec2ScannerRole-${pResourceSuffix}
      PermissionsBoundary: !Ref pPermissionsBoundaryPolicyArn
      Description: Role to be assumed by EC2 Anti-Virus Scanner instances
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Ref Ec2ScannerCwLogsPolicy
        - !Ref Ec2ScannerSqsPolicy
        - !Ref Ec2ScannerS3Policy
        - !Ref Ec2ScannerEc2Policy
        - !Ref Ec2ScannerSnsPolicy

  Ec2ScannerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${pIamPrefix}-Ec2ScannerInstanceProfile-${pResourceSuffix}
      Roles: [!Ref Ec2ScannerRole]

  TransferResultLambdaRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      RoleName: !Sub ${pIamPrefix}-TransferResultLambdaRole-${pResourceSuffix}
      PermissionsBoundary: !Ref pPermissionsBoundaryPolicyArn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: TransferResultLambdaRoleDefaultPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              # Should be locked down to only necessary SQS queue and SNS Topic
              - Effect: Allow
                Action:
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ReceiveMessage
                Resource: !Sub arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:*
              - Effect: Allow
                Action: sns:Publish
                Resource: !Sub arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:*
              - Effect: Allow
                Action: dynamodb:PutItem
                Resource: !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectTagging
                  - s3:PutObject
                  - s3:PutObjectTagging
                  - s3:DeleteObject
                  - s3:GetBucketAcl
                  - s3:ListBucket
                Resource: !Sub arn:${AWS::Partition}:s3:::*

  ObjectTaggerRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      RoleName: !Sub ${pIamPrefix}-ObjectTaggerRole-${pResourceSuffix}
      PermissionsBoundary: !Ref pPermissionsBoundaryPolicyArn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: ObjectTaggerRoleDefaultPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              # Should be locked down to only necessary SQS Queue
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: !Sub arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:*

              # Should be locked down to only necessary DynamoDB Table
              - Effect: Allow
                Action: dynamodb:PutItem
                Resource: !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:*

              - Effect: Allow
                Action:
                  - s3:GetObjectTagging
                  - s3:PutObjectTagging
                Resource: !Sub arn:${AWS::Partition}:s3:::*

  PresignGeneratorServiceRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      RoleName: !Sub ${pIamPrefix}-PresignGeneratorServiceRole-${pResourceSuffix}
      PermissionsBoundary: !Ref pPermissionsBoundaryPolicyArn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: PresignGeneratorServiceRoleDefaultPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub arn:${AWS::Partition}:s3:::*

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:*

  FileUploaderCloudWatchRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      RoleName: !Sub ${pIamPrefix}-FileUploaderCloudWatchRole-${pResourceSuffix}
      PermissionsBoundary: !Ref pPermissionsBoundaryPolicyArn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  APILambdaInvokeRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      RoleName: !Sub ${pIamPrefix}-APILambdaInvokeRole-${pResourceSuffix}
      PermissionsBoundary: !Ref pPermissionsBoundaryPolicyArn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: APILambdaInvokeRoleDefaultPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource:
                  - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:*
                  - !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*

  TransferLoggingRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      RoleName: !Sub ${pIamPrefix}-TransferLoggingRole-${pResourceSuffix}
      PermissionsBoundary: !Ref pPermissionsBoundaryPolicyArn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: transfer.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TransferLoggingPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetBucketAcl
                  - s3:PutBucketAcl
                Resource: !Sub arn:${AWS::Partition}:s3:::*
        - PolicyName: AWSTransferLoggingAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*

  TransferUserRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28 # Resource found with an explicit name, this disallows updates that require replacement of this resource
            reason: An explicit name is required
    Properties:
      RoleName: !Sub ${pIamPrefix}-TransferUserRole-${pResourceSuffix}
      PermissionsBoundary: !Ref pPermissionsBoundaryPolicyArn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: transfer.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TransferUserPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetBucketAcl
                  - s3:PutBucketAcl
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObjectVersion
                  - s3:DeleteObjectVersion
                  - s3:ListBucket
                  - s3:DeleteObject
                  - s3:GetBucketLocation
                Resource: !Sub arn:${AWS::Partition}:s3:::*

Outputs:
  TransferLoggingRoleExport:
    Description: Cloudtrail Logs Role ARN for SFTP
    Value: !GetAtt TransferLoggingRole.Arn
    Export:
      Name: !Sub TransferLoggingRoleArn-${pResourceSuffix}

  TransferUserRoleExport:
    Description: SFTP Transfer User Role ARN
    Value: !GetAtt TransferUserRole.Arn
    Export:
      Name: !Sub TransferUserRoleArn-${pResourceSuffix}

  Ec2ScannerInstanceProfileExport:
    Description: Ec2ScannerInstanceProfile ARN
    Value: !GetAtt Ec2ScannerInstanceProfile.Arn
    Export:
      Name: !Sub Ec2ScannerInstanceProfile-${pResourceSuffix}

  TransferResultLambdaRoleExport:
    Description: TransferResultLambdaRole ARN
    Value: !GetAtt TransferResultLambdaRole.Arn
    Export:
      Name: !Sub TransferResultLambdaRoleArn-${pResourceSuffix}

  ObjectTaggerRoleExport:
    Description: ObjectTaggerRole ARN
    Value: !GetAtt ObjectTaggerRole.Arn
    Export:
      Name: !Sub ObjectTaggerRoleArn-${pResourceSuffix}

  PresignGeneratorServiceRoleExport:
    Description: PresignGeneratorServiceRole ARN
    Value: !GetAtt PresignGeneratorServiceRole.Arn
    Export:
      Name: !Sub PresignGeneratorServiceRoleArn-${pResourceSuffix}

  FileUploaderCloudWatchRoleExport:
    Description: FileuploaderCloudWatchRole ARN
    Value: !GetAtt FileUploaderCloudWatchRole.Arn
    Export:
      Name: !Sub FileUploaderCloudWatchRoleArn-${pResourceSuffix}

  APILambdaInvokeRoleExport:
    Description: APILambdaInvokeRole ARN
    Value: !GetAtt APILambdaInvokeRole.Arn
    Export:
      Name: !Sub APILambdaInvokeRoleArn-${pResourceSuffix}
