environment:
  name: dev
  region: us-east-1
  account: "776732943381"

hostedZones: []

clusters:
  - name: SharedServices
    version: "1.30"
    vpc:
      id: vpc-014f5c11797a4b3d0
    nodeGroups:
      - name: compute-small
        instanceType: t3.medium
        minSize: 1
        desiredCapacity: 2
        maxSize: 3