apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-registry
  namespace: nifi
spec:
  storageClassName: standard-ssd-gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
