environment:
  name: dcw_aftac_pla_core_test_gov
  region: &region us-gov-west-1
  account: "075684568798"
  iam:
    prefix: AFC2S
    permissionBoundaryArn: arn:aws-us-gov:iam::075684568798:policy/ProjAdminPolicy
  tags:
    DNR: true
  proxy:
    httpProxy: http://proxy.tr.pri.vi2e.io:3128
    httpsProxy: http://proxy.tr.pri.vi2e.io:3128
    # noProxy: localhost,127.0.0.1,169.254.169.254,.internal,.corporate,10.0.0.0/16,192.168.0.0/16,172.20.0.0/16,.us-gov-west-1.amazonaws.com,.us-gov-west-1.eks.amazonaws.com
    noProxy:
      - localhost,127.0.0.1,169.254.169.254,.internal,.corporate,10.0.0.0/16,192.168.0.0/16,172.20.0.0/16
      # Short List of AWS Endpoints for target region

      - .autoscaling.us-gov-west-1.amazonaws.com
      - .cloudformation.us-gov-west-1.amazonaws.com
      - .cloudtrail.us-gov-west-1.amazonaws.com
      - .cloudwatch.us-gov-west-1.amazonaws.com
      - .ebs.us-gov-west-1.amazonaws.com
      - .ec2.us-gov-west-1.amazonaws.com
      - .ecr.us-gov-west-1.amazonaws.com
      - .ecs.us-gov-west-1.amazonaws.com
      - .eks.us-gov-west-1.amazonaws.com
      - .dcr.ecr.us-gov-west-1.amazonaws.com
      - .elasticfilesystem.us-gov-west-1.amazonaws.com
      - .elasticloadbalancing.us-gov-west-1.amazonaws.com
      - .kms.us-gov-west-1.amazonaws.com
      - .lambda.us-gov-west-1.amazonaws.com
      - .logs.us-gov-west-1.amazonaws.com
      - .monitoring.us-gov-west-1.amazonaws.com
      - .rds.us-gov-west-1.amazonaws.com
      - .redshift.us-gov-west-1.amazonaws.com
      - .s3.us-gov-west-1.amazonaws.com
      - .secretsmanager.us-gov-west-1.amazonaws.com
      - .ses.us-gov-west-1.amazonaws.com
      - .sns.us-gov-west-1.amazonaws.com
      - .sqs.us-gov-west-1.amazonaws.com
      - .ssm.us-gov-west-1.amazonaws.com
      - .states.us-gov-west-1.amazonaws.com
      - .storagegateway.us-gov-west-1.amazonaws.com
      - .sts.us-gov-west-1.amazonaws.com
      - .waf.us-gov-west-1.amazonaws.com
      # - .us-gov-west-1.amazonaws.com

      # EKS Cluster Endpoint
      - .us-gov-west-1.eks.amazonaws.com

  synthesizeOverride:
    cloudFormationExecutionRole: arn:aws-us-gov:iam::075684568798:role/AFC2S-cdk-hnb659fds-cfn-exec-role-075684568798-us-gov-west-1
    deployRoleArn: arn:aws-us-gov:iam::075684568798:role/AFC2S-cdk-hnb659fds-deploy-role-075684568798-us-gov-west-1
    fileAssetPublishingRoleArn: arn:aws-us-gov:iam::075684568798:role/AFC2S-cdk-hnb659fds-file-role-075684568798-us-gov-west-1
    imageAssetPublishingRoleArn: arn:aws-us-gov:iam::075684568798:role/AFC2S-cdk-hnb659fds-image-role-075684568798-us-gov-west-1
    lookupRoleArn: arn:aws-us-gov:iam::075684568798:role/AFC2S-cdk-hnb659fds-lookup-role-075684568798-us-gov-west-1
    fileAssetsBucketName: cdk-hnb659fds-assets2-075684568798-us-gov-west-1
    qualifier: hnb659fds

.vpc: &vpc
  id: vpc-0f3d92ebd7fdb9aaf

hostedZones: &hostedZones
  - zoneName: test.oneaftac.gov
    private: true
    vpc: *vpc
  - zoneName: test.oneaftac.internal
    private: true
    vpc: *vpc

.workerNodeAmi: &ami
  name: dafcw-node-eks-1.32.1-*

.controlNodeGroupSubnets: &controlNodeGroupSubnets
  - id: subnet-0b3182a2019a09d18
  - id: subnet-0a6b8dcd534a0b7c9
  - id: subnet-03b636815c657538a

.workerNodeGroupSubnets: &workerNodeGroupSubnets
  - id: subnet-0b3182a2019a09d18
  - id: subnet-0a6b8dcd534a0b7c9
  - id: subnet-03b636815c657538a

.workerNodeRhelRootstorage: &rhel-storage
  rootDeviceName: /dev/sda1
  sizeInGB: 60
  type: gp3

clusters:
  - name: Test-Shared-Services
    version: "1.32"
    private: true
    vpc:
      <<: *vpc
      subnets: *controlNodeGroupSubnets
    hostedZones: *hostedZones
    teams:
      - type: application
        name: keycloak
        namespace: keycloak
        serviceAccountName: keycloak-secrets-sa
        secrets:
          - secretName: keycloak-db-secret
            secretArn: rds!cluster-2cc4c263-3735-45b7-8fed-e728dbf0a9dd
            lookUpType: name
            metadata:
              jmesPath:
                - path: username
                  objectAlias: username
                - path: password
                  objectAlias: password
              data:
                - key: username
                  objectName: username
                - key: password
                  objectName: password
    nodeGroups:
      - name: dafcw-rhel9-compute-stig-xlarge
        instanceType: m5a.xlarge
        ami: *ami
        storage: *rhel-storage
        subnets: *workerNodeGroupSubnets
        minSize: 2
        desiredCapacity: 2
        maxSize: 50
