apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  template:
    spec:
      containers:
        - name: keycloak-operator
          env:
            - name: RELATED_IMAGE_KEYCLOAK
              value: 075684568798.dkr.ecr.us-gov-west-1.amazonaws.com/keycloak-fips:26.3.3-fips
