kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard-ssd-gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
provisioner: ebs.csi.aws.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
  encrypted: "true"
