apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: cluster-d
  namespace: nifi
spec:
  service:
    headlessEnabled: true
    labels:
      cluster-name: cluster-d
  # zkAddress: zookeeper.zookeeper:2181
  # zkPath: /nifi/cluster-d
  clusterManager: kubernetes
  clusterImage: apache/nifi:2.3.0
  initContainerImage: bash:5.2.2
  oneNifiNodePerNode: true
  readOnlyConfig:
    nifiProperties:
      webProxyHosts:
        - nifi-cluster-d.denali.jktruong.people.aws.dev
      overrideConfigMap:
        data: nifi.properties
        name: configuration
        namespace: nifi
      overrideSecretConfig:
        data: nifi.properties
        name: secret-configuration
        namespace: nifi
    logbackConfig:
      replaceConfigMap:
        data: logback.xml
        name: configuration
        namespace: nifi
  pod:
    labels:
      cluster-name: cluster-d
  nodeConfigGroups:
    default_group:
      imagePullPolicy: IfNotPresent
      isNode: true
      serviceAccountName: service-account-cluster
      storageConfigs:
        - mountPath: /opt/nifi/nifi-current/logs
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: standard-ssd-gp3
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/data
          name: data
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: standard-ssd-gp3
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/content_repository
          name: content-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: standard-ssd-gp3
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/provenance_repository
          name: provenance-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: standard-ssd-gp3
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/flowfile_repository
          name: flowfile-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: standard-ssd-gp3
            resources:
              requests:
                storage: 10Gi
      resourcesRequirements:
        limits:
          cpu: 4
          memory: 12Gi
        requests:
          cpu: "0.5"
          memory: 12Gi
  nodes:
    - id: 1
      nodeConfigGroup: default_group
      readOnlyConfig:
        nifiProperties:
          overrideConfigs: |
            nifi.ui.banner.text=NiFiKop - Node 1 // UNCLASSIFIED
    - id: 2
      nodeConfigGroup: default_group
      readOnlyConfig:
        nifiProperties:
          overrideConfigs: |
            nifi.ui.banner.text=NiFiKop - Node 2 // UNCLASSIFIED
    - id: 3
      nodeConfigGroup: default_group
      readOnlyConfig:
        nifiProperties:
          overrideConfigs: |
            nifi.ui.banner.text=NiFiKop - Node 3 // UNCLASSIFIED
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  listenersConfig:
    sslSecrets:
      tlsSecretName: web-certificate-cluster-d
      create: true
    internalListeners:
      - containerPort: 8443
        type: https
        name: https
      - containerPort: 6007
        type: cluster
        name: cluster
      - containerPort: 10000
        type: s2s
        name: s2s
      # - containerPort: 9090
      #   type: prometheus
      #   name: prometheus
      - containerPort: 6342
        name: load-balance
        type: load-balance
  externalServices:
    - name: cluster-access-cluster-d
      metadata:
        labels:
          cluster-name: cluster-d
      spec:
        portConfigs:
          - internalListenerName: https
            port: 8443
        type: LoadBalancer
  sidecarConfigs:
    - name: app-log
      image: busybox:stable
      args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-app.log
      resources: &a1
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - name: logs
          mountPath: /var/log
    - name: bootstrap-log
      image: busybox:stable
      args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-bootstrap.log
      resources: *a1
      volumeMounts:
        - name: logs
          mountPath: /var/log
    - name: user-log
      image: busybox:stable
      args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-user.log
      resources: *a1
      volumeMounts:
        - name: logs
          mountPath: /var/log
