apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service.yaml
  - cache.yaml
  - deployment.yaml

configMapGenerator:
  - name: squid-config
    files:
      - squid.conf
    namespace: squid

generatorOptions:
  disableNameSuffixHash: true
