apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-claim
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 15Gi
