apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: keycloak
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      volumes:
        - name: database-data
          persistentVolumeClaim:
            claimName: keycloak-claim
      containers:
        - name: postgresql-db
          image: postgres:16
          volumeMounts:
            - name: database-data
              mountPath: /data
          # resources:
          #   requests:
          #     cpi: "500m"
          #     memory: "1Gi"
          #   limits:
          #     cpu: "2500m"
          #     memory: "16Gi"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: password
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: keycloak

          #   - name: POSTGRES_PASSWORD
          #     value: testpassword
          #   - name: PGDATA
          #     value: /data/pgdata
          #   - name: POSTGRES_DB
          #     value: keycloak
