apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloakrealmimports.k8s.keycloak.org-v1.yml
  - keycloaks.k8s.keycloak.org-v1.yml
  - namespace.yaml
  - kubernetes.yml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: keycloak
    unsetOnly: true
