environment:
  name: standard-dev
  region: us-west-1
  account: "908027385618"
  iam:
    prefix: AFC2S
    # permissionBoundaryArn: arn:aws:iam::908027385618:policy/ProjAdminPolicy

hostedZones: &hostedZones
  - zoneName: denali.jktruong.people.aws.dev
    private: true
    vpc:
      id: &vpcId vpc-03341f2c7303b3635

.workerNodeAmi: &ami
  name: amazon-eks-node-al2023-x86_64-standard-1_30-stig-high *

.controlNodeGroupSubnets: &controlNodeGroupSubnets
  - id: subnet-0b0dad38a1d76b4b0
  - id: subnet-040bc3f3394155f31

.workerNodeGroupSubnets: &workerNodeGroupSubnets
  - id: subnet-0995934b1e5de960d
  - id: subnet-0cad71af0b2618a11

.workerNodeAlRootstorage: &al-storage
  rootDeviceName: /dev/xvda
  sizeInGB: 20
  type: gp3

.workerNodeRhelRootstorage: &rhel-storage
  rootDeviceName: /dev/sda1
  sizeInGB: 20
  type: gp3

clusters:
  - name: StandardSharedServices
    version: "1.30"
    vpc:
      id: *vpcId
      subnets: *controlNodeGroupSubnets
    hostedZones: *hostedZones
    nodeGroups:
      # - name: al2-compute-xlarge
      #   instanceType: m5a.xlarge
      #   ami:
      #     name: amazon-eks-node-1.30-*
      #   storage: *al-storage
      #   subnets: *workerNodeGroupSubnets
      #   minSize: 1
      #   desiredCapacity: 1
      #   maxSize: 40
      - name: al2023-compute-xlarge
        instanceType: m5a.xlarge
        ami:
          name: amazon-eks-node-al2023-x86_64-standard-1_30-stig-high *
        storage: *al-storage
        subnets: *workerNodeGroupSubnets
        minSize: 1
        desiredCapacity: 1
        maxSize: 50    
      # - name: al2023-compute-normal-xlarge
      #   instanceType: m5a.xlarge
      #   ami:
      #     name: amazon-eks-node-al2023-x86_64-standard-1.30-*
      #   storage: *al-storage
      #   subnets: *workerNodeGroupSubnets
      #   minSize: 1
      #   desiredCapacity: 1
      #   maxSize: 50    
      # - name: rhel8-compute-xlarge
      #   instanceType: m5a.xlarge
      #   ami:
      #     name: amazon-eks-node-rhel8-x86_64-standard-1_30-stig-high *
      #   storage: *rhel-storage
      #   subnets: *workerNodeGroupSubnets
      #   minSize: 1
      #   desiredCapacity: 1
      #   maxSize: 50
      - name: rhel9-compute-xlarge
        instanceType: m5a.xlarge
        ami:
          name: amazon-eks-node-rhel9-x86_64-standard-1_30-stig-high *
        storage: *rhel-storage
        subnets: *workerNodeGroupSubnets
        minSize: 1
        desiredCapacity: 1
        maxSize: 50
      # - name: rhel9-compute-normal-xlarge
      #   instanceType: m5a.xlarge
      #   ami:
      #     name: amazon-eks-node-rhel9-x86_64-standard-1_30-normal *
      #   storage: *rhel-storage
      #   subnets: *workerNodeGroupSubnets
      #   minSize: 1
      #   desiredCapacity: 1
      #   maxSize: 50
      # - name: rhel8-compute-normal-xlarge
      #   instanceType: m5a.xlarge
      #   ami:
      #     name: amazon-eks-node-rhel8-x86_64-standard-1_30-normal *
      #   storage: *rhel-storage
      #   subnets: *workerNodeGroupSubnets
      #   minSize: 1
      #   desiredCapacity: 1
      #   maxSize: 50
