environment:
  name: dev
  region: us-west-1
  account: "908027385618"

.storage: &storage
  type: gp3
  deviceName: /dev/xvda
  sizeInGB: 20

.vpc: &vpc
  id: vpc-040175d809b8f8b32
  subnet:
    id: subnet-086ac47d6754023ce

pipelines:
  - name: amazon-eks-node-al2023-x86_64-standard-1_30-stig-high
    description: "EKS Optimized Image with STIG High"
    version: 1.0.0
    scan: false
    # vpc: *vpc
    instanceTypes:
      - m5.large
      - m5.xlarge
      - m6a.xlarge
    ami:
      name: amazon-eks-node-al2023-x86_64-standard-1.30-*
    storages:
      - *storage
    tags:
      OS: Amazon Linux 2023
      ARCH: x86_64
      STIG: High
      FIPS: Enabled
      K8S VERSION: "1.30"
    components:
      - name: stig-build-linux-high
        version: 2024.4.0
        platform: linux
        parameters:
          - name: InstallPackages
            value: "Yes"
          - name: SetDoDConsentBanner
            value:
              - "Yes"
      - lib/component/DODSTIGHardening.yml
      - lib/component/SecurityUpdate.yml
      - lib/component/AllowEKSOperationalStatus.yml
