apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tls-certificate.yaml

# configMapGenerator:
#   - name: dod-ca-bundle
#     namespace: keycloak
#     options:
#       disableNameSuffixHash: true
#     files:
#       - external/unclass-certificates_pkcs7_DoD.zip
